version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
        - './config/elasticsearch.yml:/usr/local/bin/elasticsearch.yml'
        networks:
            - elknetwork
    kibana:
        image: kibana:7.7.0
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
         volumes:
            - ./config/kibana.yml:/usr/local/bin/kibana.yml
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.7.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - ./config/logstash.conf:/usr/local/bin/logstash.conf
          - ./config/logstash.yml:/usr/local/bin/logstash.yml
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    
    # nginx-conf:
    #     build:
    #         context: ./nginx-conf/
    #           I’mdockerfile: Dockerfile
    #     container_name: nginx
    #     restart: always
    #     ports:
    #         - 80:80
    #         - 443:443

networks:
    elknetwork:
        driver: bridge